import image from "../../../assets/image/product.png";
import image1 from "../../../assets/landing/image1.png";
export type Product = {
  id: number;
  name: string;
  category: string;
  price: string;
  status: "Active" | "Low Stock" | "Out Of Stock";
  stock: number;
  views: number;
  inquiries: number;
  date: string;
  img: string;
};

export const initialProducts: Product[] = [
  {
    id: 1,
    name: "Ultra HD Display",
    category: "Gadgets & Electronics",
    price: "$89.99",
    status: "Active",
    stock: 80,
    views: 3473,
    inquiries: 67,
    date: "17/06/2025",
    img: image,
  },
  {
    id: 2,
    name: "4K Gaming Monitor",
    category: "Fashion & Accessories",
    price: "$79.99",
    status: "Active",
    stock: 80,
    views: 3473,
    inquiries: 67,
    date: "15/08/2023",
    img: image1,
  },
  {
    id: 3,
    name: "High‑Resolution Screen",
    category: "Home & Living",
    price: "$59.99",
    status: "Low Stock",
    stock: 40,
    views: 3473,
    inquiries: 67,
    date: "22/11/2024",
    img: image,
  },
  {
    id: 4,
    name: "Crystal Clear Monitor",
    category: "Toys & Games",
    price: "$69.99",
    status: "Out Of Stock",
    stock: 0,
    views: 3473,
    inquiries: 67,
    date: "03/05/2025",
    img: image1,
  },
  {
    id: 5,
    name: "Smart Fitness Tracker",
    category: "Gadgets & Electronics",
    price: "$49.99",
    status: "Active",
    stock: 150,
    views: 2810,
    inquiries: 42,
    date: "10/06/2025",
    img: image,
  },
  {
    id: 6,
    name: "Wireless Noise-Canceling Headphones",
    category: "Fashion & Accessories",
    price: "$119.99",
    status: "Low Stock",
    stock: 25,
    views: 3962,
    inquiries: 89,
    date: "25/07/2025",
    img: image1,
  },
  {
    id: 7,
    name: "Ergonomic Office Chair",
    category: "Home & Living",
    price: "$199.99",
    status: "Active",
    stock: 60,
    views: 1789,
    inquiries: 34,
    date: "02/03/2024",
    img: image,
  },
  {
    id: 8,
    name: "Virtual Reality Headset",
    category: "Gadgets & Electronics",
    price: "$149.99",
    status: "Active",
    stock: 70,
    views: 4521,
    inquiries: 102,
    date: "19/09/2023",
    img: image1,
  },
  {
    id: 9,
    name: "Adjustable Standing Desk",
    category: "Home & Living",
    price: "$229.99",
    status: "Out Of Stock",
    stock: 0,
    views: 1354,
    inquiries: 21,
    date: "11/12/2024",
    img: image,
  },
  {
    id: 10,
    name: "LED Ring Light Set",
    category: "Toys & Games",
    price: "$39.99",
    status: "Active",
    stock: 95,
    views: 3120,
    inquiries: 58,
    date: "07/01/2025",
    img: image1,
  },
  {
    id: 11,
    name: "Bluetooth Smart Glasses",
    category: "Gadgets & Electronics",
    price: "$99.99",
    status: "Low Stock",
    stock: 18,
    views: 2740,
    inquiries: 46,
    date: "29/04/2025",
    img: image,
  },
  {
    id: 12,
    name: "Portable Projector",
    category: "Gadgets & Electronics",
    price: "$129.99",
    status: "Active",
    stock: 110,
    views: 2987,
    inquiries: 64,
    date: "13/06/2025",
    img: image1,
  },
  {
    id: 13,
    name: "Noise-Isolation Gaming Headset",
    category: "Toys & Games",
    price: "$89.00",
    status: "Active",
    stock: 55,
    views: 3881,
    inquiries: 73,
    date: "16/02/2025",
    img: image,
  },
  {
    id: 14,
    name: "Rechargeable Mini Fan",
    category: "Home & Living",
    price: "$24.99",
    status: "Out Of Stock",
    stock: 0,
    views: 2105,
    inquiries: 39,
    date: "04/08/2024",
    img: image1,
  },
  {
    id: 15,
    name: "Rechargeable Mini Fan",
    category: "Home & Living",
    price: "$24.99",
    status: "Out Of Stock",
    stock: 0,
    views: 2105,
    inquiries: 39,
    date: "04/08/2024",
    img: image,
  },
];

import { z } from "zod";

export const ProductSchema = z.object({
  id: z.number(),
  name: z.string().min(1),
  category: z.string().min(1),
  price: z.string().regex(/^\$\d+(\.\d{2})?$/, "Invalid price"),
  status: z.enum(["Active", "Low Stock", "Out Of Stock"]),
  stock: z.number().min(0),
  views: z.number().min(0),
  inquiries: z.number().min(0),
  date: z.string().regex(/^\d{2}\/\d{2}\/\d{4}$/, "DD/MM/YYYY required"),
  img: z.string(),
});

export type ProductFormData = z.infer<typeof ProductSchema>;
