import image1 from "../../assets/Manufacturer/Rectangle 5.png";
import image2 from "../../assets/Manufacturer/Rectangle 6.png";
import { default as image3, default as image4 } from "../../assets/Manufacturer/Rectangle 7.png";

export interface Manufacturer {
  id: number;
  shopName: string;
  name: string;
  location: string;
  rating: number;
  totalReviews: number;
  images: string[];
}

export const manufacturers: Manufacturer[] = [
  {
    id: 1,
    shopName: "Samsung Electronics",
    name: "Samsung",
    location: "Seoul, South Korea",
    rating: 4.9,
    totalReviews: 1200,
    images: [image1, image2, image3, image4],
  },
  {
    id: 2,
    shopName: "Apple Store",
    name: "Apple",
    location: "California, USA",
    rating: 4.8,
    totalReviews: 1500,
    images: [image1, image2, image3, image4],
  },
  {
    id: 3,
    shopName: "Sony Corporation",
    name: "Sony",
    location: "Tokyo, Japan",
    rating: 4.7,
    totalReviews: 980,
    images: [image1, image2, image3, image4],
  },
  {
    id: 4,
    shopName: "LG Electronics",
    name: "LG",
    location: "Seoul, South Korea",
    rating: 4.6,
    totalReviews: 875,
    images: [image1, image2, image3, image4],
  },
  {
    id: 5,
    shopName: "Samsung Digital Plaza",
    name: "Samsung",
    location: "Suwon, South Korea",
    rating: 4.7,
    totalReviews: 1025,
    images: [image1, image2, image3, image4],
  },
  {
    id: 6,
    shopName: "Sony Center",
    name: "Sony",
    location: "Tokyo, Japan",
    rating: 4.5,
    totalReviews: 740,
    images: [image1, image2, image3, image4],
  },
  {
    id: 7,
    shopName: "Panasonic Global",
    name: "Panasonic",
    location: "Osaka, Japan",
    rating: 4.4,
    totalReviews: 680,
    images: [image1, image2, image3, image4],
  },
  {
    id: 8,
    shopName: "Huawei Store",
    name: "Huawei",
    location: "Shenzhen, China",
    rating: 4.3,
    totalReviews: 800,
    images: [image1, image2, image3, image4],
  },
  {
    id: 9,
    shopName: "Dell Technologies",
    name: "Dell",
    location: "Texas, USA",
    rating: 4.5,
    totalReviews: 910,
    images: [image1, image2, image3, image4],
  },
  {
    id: 10,
    shopName: "HP Inc.",
    name: "HP",
    location: "California, USA",
    rating: 4.2,
    totalReviews: 720,
    images: [image1, image2, image3, image4],
  },
  {
    id: 11,
    shopName: "Lenovo Group",
    name: "Lenovo",
    location: "Beijing, China",
    rating: 4.4,
    totalReviews: 850,
    images: [image1, image2, image3, image4],
  },
  {
    id: 12,
    shopName: "AsusTek Computer",
    name: "Asus",
    location: "Taipei, Taiwan",
    rating: 4.3,
    totalReviews: 780,
    images: [image1, image2, image3, image4],
  },
  {
    id: 13,
    shopName: "Acer Inc.",
    name: "Acer",
    location: "Taipei, Taiwan",
    rating: 4.1,
    totalReviews: 630,
    images: [image1, image2, image3, image4],
  },
  {
    id: 14,
    shopName: "Microsoft Store",
    name: "Microsoft",
    location: "Redmond, USA",
    rating: 4.8,
    totalReviews: 1100,
    images: [image1, image2, image3, image4],
  },
  {
    id: 15,
    shopName: "Google Hardware",
    name: "Google",
    location: "Mountain View, USA",
    rating: 4.7,
    totalReviews: 1000,
    images: [image1, image2, image3, image4],
  },
  {
    id: 16,
    shopName: "OnePlus Store",
    name: "OnePlus",
    location: "Shenzhen, China",
    rating: 4.6,
    totalReviews: 780,
    images: [image1, image2, image3, image4],
  },
  {
    id: 17,
    shopName: "Xiaomi Global",
    name: "Xiaomi",
    location: "Beijing, China",
    rating: 4.5,
    totalReviews: 900,
    images: [image1, image2, image3, image4],
  },
  {
    id: 18,
    shopName: "Amazon Devices",
    name: "Amazon",
    location: "Seattle, USA",
    rating: 4.4,
    totalReviews: 850,
    images: [image1, image2, image3, image4],
  },
  {
    id: 19,
    shopName: "Bose Corporation",
    name: "Bose",
    location: "Massachusetts, USA",
    rating: 4.6,
    totalReviews: 730,
    images: [image1, image2, image3, image4],
  },
  {
    id: 20,
    shopName: "Canon Inc.",
    name: "Canon",
    location: "Tokyo, Japan",
    rating: 4.3,
    totalReviews: 670,
    images: [image1, image2, image3, image4],
  },
  {
    id: 21,
    shopName: "Nikon Corporation",
    name: "Nikon",
    location: "Tokyo, Japan",
    rating: 4.2,
    totalReviews: 600,
    images: [image1, image2, image3, image4],
  },
  {
    id: 22,
    shopName: "GoPro Inc.",
    name: "GoPro",
    location: "California, USA",
    rating: 4.1,
    totalReviews: 520,
    images: [image1, image2, image3, image4],
  },
  {
    id: 23,
    shopName: "DJI Technology",
    name: "DJI",
    location: "Shenzhen, China",
    rating: 4.7,
    totalReviews: 800,
    images: [image1, image2, image3, image4],
  },
  {
    id: 24,
    shopName: "Fitbit Inc.",
    name: "Fitbit",
    location: "San Francisco, USA",
    rating: 4.2,
    totalReviews: 680,
    images: [image1, image2, image3, image4],
  },
  {
    id: 25,
    shopName: "Garmin Ltd.",
    name: "Garmin",
    location: "Kansas, USA",
    rating: 4.4,
    totalReviews: 750,
    images: [image1, image2, image3, image4],
  },
  {
    id: 26,
    shopName: "JBL Audio",
    name: "JBL",
    location: "Los Angeles, USA",
    rating: 4.3,
    totalReviews: 690,
    images: [image1, image2, image3, image4],
  },
  {
    id: 27,
    shopName: "Alienware",
    name: "Alienware",
    location: "Texas, USA",
    rating: 4.6,
    totalReviews: 810,
    images: [image1, image2, image3, image4],
  },
  {
    id: 28,
    shopName: "Razer Inc.",
    name: "Razer",
    location: "San Francisco, USA",
    rating: 4.5,
    totalReviews: 770,
    images: [image1, image2, image3, image4],
  },
  {
    id: 29,
    shopName: "Logitech International",
    name: "Logitech",
    location: "Lausanne, Switzerland",
    rating: 4.4,
    totalReviews: 720,
    images: [image1, image2, image3, image4],
  },
  {
    id: 30,
    shopName: "Corsair Gaming",
    name: "Corsair",
    location: "California, USA",
    rating: 4.3,
    totalReviews: 680,
    images: [image1, image2, image3, image4],
  },
  {
    id: 31,
    shopName: "Seagate Technology",
    name: "Seagate",
    location: "California, USA",
    rating: 4.2,
    totalReviews: 650,
    images: [image1, image2, image3, image4],
  },
  {
    id: 32,
    shopName: "Western Digital",
    name: "Western Digital",
    location: "California, USA",
    rating: 4.3,
    totalReviews: 700,
    images: [image1, image2, image3, image4],
  },
  {
    id: 33,
    shopName: "Sandisk Corporation",
    name: "Sandisk",
    location: "California, USA",
    rating: 4.4,
    totalReviews: 720,
    images: [image1, image2, image3, image4],
  },
  {
    id: 34,
    shopName: "Netgear Inc.",
    name: "Netgear",
    location: "California, USA",
    rating: 4.1,
    totalReviews: 600,
    images: [image1, image2, image3, image4],
  },
  {
    id: 35,
    shopName: "TP-Link Technologies",
    name: "TP-Link",
    location: "Shenzhen, China",
    rating: 4.0,
    totalReviews: 550,
    images: [image1, image2, image3, image4],
  },
  {
    id: 36,
    shopName: "Belkin International",
    name: "Belkin",
    location: "California, USA",
    rating: 4.2,
    totalReviews: 620,
    images: [image1, image2, image3, image4],
  },
  {
    id: 37,
    shopName: "Epson Corporation",
    name: "Epson",
    location: "Tokyo, Japan",
    rating: 4.3,
    totalReviews: 680,
    images: [image1, image2, image3, image4],
  },
  {
    id: 38,
    shopName: "Brother Industries",
    name: "Brother",
    location: "Nagoya, Japan",
    rating: 4.1,
    totalReviews: 600,
    images: [image1, image2, image3, image4],
  },
  {
    id: 39,
    shopName: "Kyocera Corporation",
    name: "Kyocera",
    location: "Kyoto, Japan",
    rating: 4.0,
    totalReviews: 570,
    images: [image1, image2, image3, image4],
  },
  {
    id: 40,
    shopName: "Sharp Corporation",
    name: "Sharp",
    location: "Osaka, Japan",
    rating: 4.1,
    totalReviews: 590,
    images: [image1, image2, image3, image4],
  },
  {
    id: 41,
    shopName: "Vizio Inc.",
    name: "Vizio",
    location: "California, USA",
    rating: 4.2,
    totalReviews: 620,
    images: [image1, image2, image3, image4],
  },
  {
    id: 42,
    shopName: "TCL Corporation",
    name: "TCL",
    location: "Huizhou, China",
    rating: 4.1,
    totalReviews: 580,
    images: [image1, image2, image3, image4],
  },
  {
    id: 43,
    shopName: "Hisense Group",
    name: "Hisense",
    location: "Qingdao, China",
    rating: 4.0,
    totalReviews: 550,
    images: [image1, image2, image3, image4],
  },
  {
    id: 44,
    shopName: "Sharp Electronics",
    name: "Sharp",
    location: "Osaka, Japan",
    rating: 4.1,
    totalReviews: 600,
    images: [image1, image2, image3, image4],
  },
  {
    id: 45,
    shopName: "Philips Electronics",
    name: "Philips",
    location: "Amsterdam, Netherlands",
    rating: 4.3,
    totalReviews: 670,
    images: [image1, image2, image3, image4],
  },
  {
    id: 46,
    shopName: "Sennheiser Electronics",
    name: "Sennheiser",
    location: "Wedemark, Germany",
    rating: 4.4,
    totalReviews: 700,
    images: [image1, image2, image3, image4],
  },
  {
    id: 47,
    shopName: "Bang & Olufsen",
    name: "B&O",
    location: "Struer, Denmark",
    rating: 4.5,
    totalReviews: 750,
    images: [image1, image2, image3, image4],
  },
  {
    id: 48,
    shopName: "JVC Kenwood",
    name: "JVC",
    location: "Kanagawa, Japan",
    rating: 4.2,
    totalReviews: 630,
    images: [image1, image2, image3, image4],
  },
  {
    id: 49,
    shopName: "Yamaha Corporation",
    name: "Yamaha",
    location: "Hamamatsu, Japan",
    rating: 4.3,
    totalReviews: 670,
    images: [image1, image2, image3, image4],
  },
  {
    id: 50,
    shopName: "Toshiba Corporation",
    name: "Toshiba",
    location: "Tokyo, Japan",
    rating: 4.1,
    totalReviews: 610,
    images: [image1, image2, image3, image4],
  }
];
