import img from '../../assets/Reuseable/prodcut2.png';

export const pendingReviews = [
  {
    productId: "BT-EARBUDS-BLACK",
    productName: "Bluetooth Wireless Earbuds with Deep Bass, 40H Playtime",
    vendorName: "Fitness Zone",
    vendorLogo: img,
    vendorRating: 4.8,
    productCategory: "Electronics",
    vendorLocation: "222 Maple St, USA",
    orderDetails: [
      {
        variant: "Black",
        quantity: 10,
        price: "$1200",
        orderDate: "17/06/2025",
        image: img,
      },
      // {
      //   variant: "Pink",
      //   quantity: 10,
      //   price: "$1200",
      //   orderDate: "17/06/2025",
      //   image: img,
      // },
    ],
  },
  {
    productId: "SMARTHOME-THERMOSTAT",
    productName: "Smart Home Thermostat with Voice Control",
    vendorName: "SmartHome Inc.",
    vendorLogo: img,
    vendorRating: 4.6,
    productCategory: "Home Automation",
    vendorLocation: "123 Tech Ave, Silicon Valley, USA",
    orderDetails: [
      {
        variant: "Black",
        quantity: 5,
        price: "$299",
        orderDate: "20/06/2025",
        image: img,
      },
      {
        variant: "White",
        quantity: 8,
        price: "$299",
        orderDate: "20/06/2025",
        image: img,
      },
    ],
  },
  {
    productId: "OLED-TV-55",
    productName: "55-inch OLED TV with 4K HDR",
    vendorName: "TechStore",
    vendorLogo: img,
    vendorRating: 4.9,
    productCategory: "Electronics",
    vendorLocation: "500 Tech Blvd, San Francisco, USA",
    orderDetails: [
      {
        variant: "Black",
        quantity: 2,
        price: "$1500",
        orderDate: "18/06/2025",
        image: img,
      },
      {
        variant: "Silver",
        quantity: 3,
        price: "$1500",
        orderDate: "18/06/2025",
        image: img,
      },
    ],
  },
  {
    productId: "WASHER-X1000",
    productName: "X1000 Smart Washing Machine with Auto Load Detection",
    vendorName: "LaundryTech",
    vendorLogo: img,
    vendorRating: 4.7,
    productCategory: "Home Appliances",
    vendorLocation: "788 Laundry Rd, Wash City, USA",
    orderDetails: [
      {
        variant: "White",
        quantity: 3,
        price: "$850",
        orderDate: "15/06/2025",
        image: img,
      },
      {
        variant: "Silver",
        quantity: 4,
        price: "$850",
        orderDate: "15/06/2025",
        image: img,
      },
    ],
  },
  {
    productId: "GAMING-LAPTOP-XR",
    productName: "Gaming Laptop XR with RTX 3070, 16GB RAM",
    vendorName: "GameTech",
    vendorLogo: img,
    vendorRating: 4.5,
    productCategory: "Computers",
    vendorLocation: "1000 GameTech Way, Seattle, USA",
    orderDetails: [
      {
        variant: "Black",
        quantity: 2,
        price: "$2000",
        orderDate: "22/06/2025",
        image: img,
      },
      {
        variant: "Silver",
        quantity: 4,
        price: "$2000",
        orderDate: "22/06/2025",
        image: img,
      },
    ],
  },
  {
    productId: "ELECTRIC-BIKE-BOOSTER",
    productName: "Electric Bike Booster with 50KM Range",
    vendorName: "GreenMobility",
    vendorLogo: img,
    vendorRating: 4.4,
    productCategory: "Transportation",
    vendorLocation: "789 Green St, EcoCity, USA",
    orderDetails: [
      {
        variant: "Black",
        quantity: 1,
        price: "$1200",
        orderDate: "25/06/2025",
        image: img,
      },
      {
        variant: "White",
        quantity: 2,
        price: "$1200",
        orderDate: "25/06/2025",
        image: img,
      },
    ],
  }
];

export const reviewedData = [
  {
    productId: "BT-EARBUDS-BLACK",
    productName: "Bluetooth Wireless Earbuds with Deep Bass",
    vendorName: "Fitness Zone",
    vendorLogo: img,
    vendorLocation: "222 Maple St, USA",
    vendorRating: 4.8,
    productCategory: "Electronics",
    orderDetails: [
      {
        variant: "Black",
        quantity: 10,
        price: "$1200",
        orderDate: "17/06/2025",
        image: img,
      },
      {
        variant: "Pink",
        quantity: 5,
        price: "$1200",
        orderDate: "18/06/2025",
        image: img,
      },
    ],
    userReview:
      "I bought a set of handmade ceramic mugs from this seller, and I'm thrilled! The quality is excellent, colors are vibrant, and shipping was quick. I highly recommend this seller for unique pottery!I highly recommend this seller for unique pottery!I highly recommend this seller for unique pottery!I highly recommend this seller for unique pottery!",
    userRating: 5,
  },
  {
    productId: "SMARTHOME-THERMOSTAT",
    productName: "Smart Home Thermostat with Voice Control",
    vendorName: "SmartHome Inc.",
    vendorLogo: img,
    vendorLocation: "456 Oak St, USA",
    vendorRating: 4.6,
    productCategory: "Home Automation",
    orderDetails: [
      {
        variant: "White",
        quantity: 3,
        price: "$299",
        orderDate: "20/06/2025",
        image: img,
      },
    ],
    userReview: "The thermostat works great! It's easy to set up and integrates well with my smart home system. Very happy with my purchase.",
    userRating: 4,
  },
  {
    productId: "OLED-TV-55",
    productName: "55-inch OLED TV with 4K HDR",
    vendorName: "TechStore",
    vendorLogo: img,
    vendorLocation: "789 Pine St, USA",
    vendorRating: 4.9,
    productCategory: "Electronics",
    orderDetails: [
      {
        variant: "Black",
        quantity: 1,
        price: "$1500",
        orderDate: "18/06/2025",
        image: img,
      },
    ],
    userReview:
      "The picture quality is amazing! The 4K HDR is crystal clear, and the sound is rich. Highly recommend this TV for anyone looking for top-notch performance.",
    userRating: 5,
  },
  {
    productId: "WASHER-X1000",
    productName: "X1000 Smart Washing Machine with Auto Load Detection",
    vendorName: "LaundryTech",
    vendorLogo: img,
    vendorLocation: "123 Birch St, USA",
    vendorRating: 4.7,
    productCategory: "Home Appliances",
    orderDetails: [
      {
        variant: "White",
        quantity: 2,
        price: "$850",
        orderDate: "22/06/2025",
        image: img,
      },
    ],
    userReview:
      "This washing machine is great! It's super efficient and quiet. The auto load detection feature is a lifesaver. Worth every penny!",
    userRating: 4,
  },
  {
    productId: "GAMING-LAPTOP-XR",
    productName: "Gaming Laptop XR with RTX 3070, 16GB RAM",
    vendorName: "GameTech",
    vendorLogo: img,
    vendorLocation: "321 Elm St, USA",
    vendorRating: 4.5,
    productCategory: "Computers",
    orderDetails: [
      {
        variant: "Black",
        quantity: 2,
        price: "$2000",
        orderDate: "25/06/2025",
        image: img,
      },
    ],
    userReview:
      "This laptop is a beast! Handles everything from gaming to professional work with ease. The build quality is top-notch.",
    userRating: 5,
  },
  {
    productId: "ELECTRIC-BIKE-BOOSTER",
    productName: "Electric Bike Booster with 50KM Range",
    vendorName: "GreenMobility",
    vendorLogo: img,
    vendorLocation: "456 Oak St, USA",
    vendorRating: 4.4,
    productCategory: "Transportation",
    orderDetails: [
      {
        variant: "Black",
        quantity: 1,
        price: "$1200",
        orderDate: "30/06/2025",
        image: img,
      },
    ],
    userReview:
      "Love this electric bike! It's fast, efficient, and the range is perfect for my daily commute. I highly recommend it to anyone looking for eco-friendly transportation.",
    userRating: 4,
  },
  {
    productId: "SMARTWATCH-5000",
    productName: "Smartwatch 5000 with Health Monitoring",
    vendorName: "HealthGear",
    vendorLogo: img,
    vendorLocation: "789 Cedar St, USA",
    vendorRating: 4.7,
    productCategory: "Wearables",
    orderDetails: [
      {
        variant: "Silver",
        quantity: 1,
        price: "$250",
        orderDate: "05/07/2025",
        image: img,
      },
    ],
    userReview:
      "Great smartwatch! Tracks all my health metrics and the battery lasts forever. Very comfortable to wear and stylish as well.",
    userRating: 5,
  },
  {
    productId: "TABLET-2025",
    productName: "10-inch Tablet with 4GB RAM, 128GB Storage",
    vendorName: "TabTech",
    vendorLogo: img,
    vendorLocation: "102 Pine St, USA",
    vendorRating: 4.3,
    productCategory: "Electronics",
    orderDetails: [
      {
        variant: "Space Gray",
        quantity: 3,
        price: "$350",
        orderDate: "08/07/2025",
        image: img,
      },
    ],
    userReview:
      "This tablet is fast, has a great screen, and is perfect for work and entertainment. The storage and RAM are sufficient for multitasking.",
    userRating: 4,
  },
  {
    productId: "WIFI-ROUTER-2000",
    productName: "WiFi Router 2000 with Dual Band Speed",
    vendorName: "TechNet",
    vendorLogo: img,
    vendorLocation: "111 Maple St, USA",
    vendorRating: 4.6,
    productCategory: "Networking",
    orderDetails: [
      {
        variant: "Black",
        quantity: 2,
        price: "$150",
        orderDate: "10/07/2025",
        image: img,
      },
    ],
    userReview:
      "Good performance, great range, and easy setup. Perfect for a home office or streaming in multiple rooms. Very happy with this purchase.",
    userRating: 4,
  },
];